---
# This script contains commands to manage "Profile workflow" and install site from scratch by using installation profile.
- name: Droping drupal database
  mysql_db: name={{ mysql_db }} state=absent login_user={{ mysql_user }} login_password={{ mysql_pass }}

- name: Creating drupal database
  mysql_db: name={{ mysql_db }} state=present login_user={{ mysql_user }} login_password={{ mysql_pass }}

- name: Remove settings.php
  file: name={{ settings_file_path }} state=absent
  become: yes
  when: run_installation_process
  
- name: Getting name for settings (WINDOWS)
  set_fact: platform_settings_file={{ tmp_folder }}/reinstall_settings.php
  when: is_windows

- name: Getting name for settings (UNIX)
  set_fact: platform_settings_file={{ settings_file_path }}
  when: is_windows == false

#- name: Remove settings.php
#  file: name={{ settings_file_path }} state=absent
#  become: yes
#  when: run_installation_process

- name: Creating settings.php
  become: yes
  shell: "cp {{ settings_default_file_path }} {{ platform_settings_file }}"
  when: run_installation_process

- name: Installing drupal
  become: yes
  shell: "{{ php_env_vars }} drush -y si {{ installation_profile_name }} {{ openy_profile_install_settings }} openy_terms_of_use.agree_openy_terms=1 install_configure_form.enable_update_status_emails=NULL --db-url=mysql://{{ mysql_user }}:{{ mysql_pass }}@127.0.0.1:/{{ mysql_db }} --account-name={{ drupal_user }} --account-pass={{ drupal_pass }} --uri={{ site_url }}"
  when: run_installation_process
